# 21、 章错误处理与调试

## 一、浏览器错误报告

### 1、桌面控制台

>不同操作系统和浏览器支持不同的快捷键
>
>| 浏 览 器 | Windows/Linux    | Mac       |
>| -------- | ---------------- | --------- |
>| Chrome   | Ctrl+Shfit+J     | Cmd+Opt+J |
>| Firefox  | Ctrl+Shfit+K     | Cmd+Opt+K |
>| IE/Edge  | F12，然后 Ctrl+2 | 不适用    |
>| Opera    | Ctrl+Shift+I     | Cmd+Opt+I |
>| Safari   | 不适用           | Cmd+Opt+C |
>
>移动端
>
>>1、比如 Chrome 的操作步骤参见 Google Developers 网站的文章《Android 设备的远程调试入门》，
>>
>>2、Safari 的操作步骤参见 Apple Developer 网站的文章“Safari Web Inspector Guide”。

## 二、错误处理

### 1、**try**/**catch** 语句

>**try**/**catch**语句
>
>````
>try { 
> window.someNonexistentFunction(); 
>} catch (error){ 
> console.log("An error happened!"); 
>} // window.someNonexistentFunction is not a function
>````
>
>1. **finally** 子句
>
>>try 块中的代码运行完，则接着执行finally 块中的代码。如果出错并执行 catch 块中的代码，则 finally 块中的代码仍执行。try 或catch 块无法阻止 finally 块执行.
>>
>>function testFinally(){ 
>>
>> try { 
>>
>>  return 2; 
>>
>> } catch (error){ 
>>
>>  return 1; 
>>
>> } finally { 
>>
>>  return 0; 
>>
>> }  // 0
>
>**2.错误类型**
>
>> Error:  Error 是基类型，其他错误类型继承该类型。 开发者自定义错误。
>>
>> InternalError：错误会在底层 JavaScript 引擎抛出异常时由浏览器抛出。递归过多导
>>
>>​								致了栈溢出。很可能代码哪里弄错了或者有危险了。
>>
>> EvalError : 错误会在使用 eval()函数发生异常时抛出; 但浏览器有所差异。
>>
>> RangeError: 错误会在数值越界时抛出。
>>
>> ReferenceError： 会在找不到对象时发生。这种错误经常是由访问不存在的变量而导									致的
>>
>> SyntaxError： 经常在给 eval()传入的字符串包含 JavaScript 语法错误时发生。很少会用到 SyntaxError。这是因为JavaScript 代码中的语法错误会导致代码无法执行
>>
>> TypeError：在 JavaScript 中很常见，主要发生在变量不是预期类型，或者访问不存在的方法时。很
>>
>>多原因可能导致这种错误，尤其是在使用类型特定的操作而变量类型不对时。
>>
>> URIError：使用 encodeURI()或 decodeURI()但传入了格式错误的URI 时发生。
>>
>>**错误类型处理**
>>
>>````js
>>不同的错误类型可用于为异常提供更多信息，以便实现适当的错误处理逻辑。在 try/catch 语句
>>的 catch 块中，可以使用 instanceof 操作符确定错误的类型
>>try { 
>> someFunction(); 
>>} catch (error){ 
>> if (error instanceof TypeError){
>> // 处理类型错误
>> } else if (error instanceof ReferenceError){ 
>> // 处理引用错误
>> } else { 
>> // 处理所有其他类型的错误
>> } 
>>}
>>//检查错误类型是以跨浏览器方式确定适当操作过程的最简单方法，因为 message 属性中包含的错
>>误消息因浏览器而异.
>>````

### 2、抛出错误(throw)

>
>
>````js
>try {
>   throw new SyntaxError("I don't like your syntax."); 
>   throw new InternalError("I can't do that, Dave."); 
>   throw new TypeError("What type of variable do you take me for?"); 
>   throw new RangeError("Sorry, you just don't have the range."); 
>   throw new EvalError("That doesn't evaluate."); 
>   throw new URIError("Uri, is that you?"); 
>   throw new ReferenceError("You didn't cite your references properly.");
>} catch(err) {
>   console.error(err)
>}
>````
>
>**抛出错误与 try/catch**
>
>>至于抛出错误与捕获错误的区别，可以这样想：应该只在确切知道接下来该做什么的时候捕获错
>>
>>误。捕获错误的目的是阻止浏览器以其默认方式响应；抛出错误的目的是为错误提供有关其发生原因的
>>
>>说明。

### 3、error事件

> 任何没有被 try/catch 语句处理的错误都会在 window 对象上触发 error 事件。该事件是浏览器早期支持的事件，为保持向后兼容，很多浏览器保持了其格式不变。（这个事件处理程序应该是处理浏览器报告错误的最后一道防线，理想情况下，最好永远不要用到。）

>***注意** 浏览器在使用这个事件处理错误时存在明显差异。在 IE 中发生 error 事件时，正
>
>常代码会继续执行，所有变量和数据会保持，且可以在 onerror 事件处理程序中访问。
>
>然而在 Firefox 中，正常代码会执行会终止，错误发生之前的所有变量和数据会被销毁，
>
>导致很难真正分析处理错误。

#### 4、识别错误

>通常，需要注意 3 类错误：
>
>​	 类型转换错误
>
>​	 数据类型错误
>
>​	 通信错误
>
>**1.静态代码分析器**
>
>>GitHub Gist 网站 All Gists 页面; 常用的静态分析工具是 JSHint、JSLint、Google Closure 和 TypeScript
>>
>>***注意** 随着代码数量的增长，代码分析器会变得越来越重要，尤其是协作开发者也在增加的情况下。所有主流技术公司都有着庞大的 JavaScript 库，并会在构建流程中使用稳健的静态分析工具。
>
>**2.类型转换错误**
>
>````js
>function concat(str1, str2, str3) { 
> let result = str1 + str2; 
> if (str3) { // 不要！
> result += str3; 
> } 
> return result; 
>}
>
>/*换中，undefined 会被转换为布尔值 false。因此这个函数的用意是在提供了第三个参数的情况下，
>才会在拼接时带上它。问题在于并非只有undefined会转换为false，字符串也不是唯一可转换为true
>的值。假如第三个参数是数值 0，if 条件判断就会失败，而数值 1 则会导致满足条件。
>在流控制语句中使用非布尔值作为条件是很常见的错误来源。为避免这类错误，需要始终坚持使用
>布尔值作为条件。这通常可以借助某种比较来实现。*/
>function concat(str1, str2, str3){ 
> let result = str1 + str2; 
> if (typeof str3 === "string") { // 恰当的比较
> result += str3; 
> } 
> return result; 
>} 
>//在这个重写的版本中，if 语句的条件会基于比较操作返回布尔值。这个函数相对更安全，受错误值影响的可能性也更小。
>````
>
>**3.数据类型错误**
>
>>// 不安全的函数，任何非字符串值都会导致错误
>>
>>function getQueryString(url) { 
>>
>>​          const pos = url.indexOf("?"); 
>>
>>​    if (pos > -1){ 
>>
>>​         return url.substring(pos +1); 
>>
>>​    } 
>>
>>​     return ""; 
>>
>>} 
>>
>>正确类型：  确保使用参数时自己想要的类型参数。校验时需要精确到明确类型。不要用js隐士进行校验。每个参数都有必要进行校验。
>>
>>function getQueryString(url) { 
>>
>> **if (typeof url === "string") { //** **通过类型检查保证安全**
>>
>> let pos = url.indexOf("?"); 
>>
>> if (pos > -1) { 
>>
>> return url.substring(pos +1); 
>>
>> } 
>>
>> **}** 
>>
>> return ""; 
>>
>>} 
>

## 三、调试技术

> error(*message*)：在控制台中记录错误消息。
>
> info(*message*)：在控制台中记录信息性内容。
>
> log(*message*)：在控制台记录常规消息。
>
> warn(*message*)：在控制台中记录警告消息。
>
>**补充控制台方法**
>
>````
>// 把所有参数拼接为一个字符串，然后打印出结果
>console.log = function() { 
> // 'arguments'并没有 join 方法，这里先把它转换为数组
> const args = Array.prototype.slice.call(arguments); 
> console.log(args.join(', ')); 
>}
>````

#### 抛出错误

>抛出错误是调试代码的很好方式。如果错误消息足够具体，只要看一眼错误就可以确定原因。好的错误消息包含关于错误原因的确切信息，因此可以减少额外调试的工作量。
>
>````js
>function divide(num1, num2) { 
> return num1 / num2; 
>}
>````
>
>函数执行两个数的除法，但如果任何一个参数不是数值，则返回 NaN。当 Web 应用程序意外返回 NaN 时，简单的计算可能就会出问题。
>
>`````js
>function divide(num1, num2) { 
> if (typeof num1 != "number" || typeof num2 != "number"){ 
> throw new Error("divide(): Both arguments must be numbers."); 
> }
> return num1 / num2; 
>}
>`````
>
>在大型应用程序中，自定义错误通常使用 assert()函数抛出错误。这个函数接收一个应该为 true的条件，并在条件为 false 时抛出错误。
>
>```js
>function assert(condition, message) { 
> if (!condition) { 
> throw new Error(message); 
> } 
>}
>//这个 assert()函数可用于代替多个 if 语句，同时也是记录错误的好地方。
>function divide(num1, num2) { 
> assert(typeof num1 == "number" && typeof num2 == "number", 
> "divide(): Both arguments must be numbers."); 
> return num1 / num2; 
>}
>// 使用 assert()函数可以减少抛出自定义错误所需的代码量，并且让代码更好理解
>```
>
>



